name: sealed_generator
description: Code gen for flutter&#x27;s sealed classes
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^1.1.5
  meta: ^1.1.7
  source_gen: ^0.9.4+3
  recase: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^0.10.0
  build_runner: ^1.0.0
  test: ^1.0.0

flutter: